### ISSUE TITLE
Responding even if there is no image provided 

### ISSUE THREAD

**Issue by MervinPraison** [matatonic/openedai-vision#5]
I tried to integrate this with a Chat Interface. 
If I provide image its working, if I don't provide image its breaking. 

Please make it to work for both, so that it can easily be integrated with any application, which can handle both image and text or text only or image only. 

This is what happened when I tried only with Text: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Ubuntu/miniconda3/envs/openedai/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Ubuntu/miniconda3/envs/openedai/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Ubuntu/miniconda3/envs/openedai/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/Ubuntu/miniconda3/envs/openedai/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/Ubuntu/miniconda3/envs/openedai/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/Ubuntu/miniconda3/envs/openedai/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/Ubuntu/miniconda3/envs/openedai/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/home/Ubuntu/miniconda3/envs/openedai/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/Ubuntu/miniconda3/envs/openedai/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/home/Ubuntu/miniconda3/envs/openedai/lib/python3.11/site-packages/sse_starlette/sse.py", line 273, in wrap
    await func()
  File "/home/Ubuntu/miniconda3/envs/openedai/lib/python3.11/site-packages/sse_starlette/sse.py", line 253, in stream_response
    async for data in self.body_iterator:
  File "/home/Ubuntu/openedai-vision/vision.py", line 59, in streamer
    async for resp in vision_qna.stream_chat_with_images(request):
  File "/home/Ubuntu/openedai-vision/backend/llavanext.py", line 34, in stream_chat_with_images
    inputs = self.processor(prompt, images, return_tensors="pt").to(self.model.device)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Ubuntu/miniconda3/envs/openedai/lib/python3.11/site-packages/transformers/models/llava_next/processing_llava_next.py", line 110, in __call__
    image_inputs = self.image_processor(images, do_pad=do_pad, return_tensors=return_tensors)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Ubuntu/miniconda3/envs/openedai/lib/python3.11/site-packages/transformers/image_processing_utils.py", line 41, in __call__
    return self.preprocess(images, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Ubuntu/miniconda3/envs/openedai/lib/python3.11/site-packages/transformers/models/llava_next/image_processing_llava_next.py", line 678, in preprocess
    images = make_batched_images(images)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Ubuntu/miniconda3/envs/openedai/lib/python3.11/site-packages/transformers/models/llava_next/image_processing_llava_next.py", line 67, in make_batched_images
    if isinstance(images, (list, tuple)) and isinstance(images[0], (list, tuple)) and is_valid_image(images[0][0]):
                                                        ~~~~~~^^^
IndexError: list index out of range

**Comment by matatonic** [comment]
Thanks for the report, will be fixed in next release. llava requires an image, but I can pass a single transparent pixel to prevent any errors.
